# Base image for both development and production
FROM node:22 AS base

WORKDIR /app

COPY package*.json ./

RUN npm ci
RUN npm install --save-dev @vitejs/plugin-react-swc

COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev", "--host", "0.0.0.0"]